### ISSUE TITLE
Unable to create a new user

### ISSUE THREAD

**Issue by franck-boullier** [Unee-T-INS/frontend#10]
# The test:

In http://case.dev.ins.unee-t.com/signup
Create a new user

## Expected result:
The new user is created

## Actual result:

Endless loading page and the user is not created.
![image](https://user-images.githubusercontent.com/31331637/72491481-20176080-3855-11ea-8ec9-8036afd214bc.png)

**Comment by franck-boullier** [comment]
More information: check if the Master API key for the BZ installation is correct: DONE <-- the parameter `BUGZILLA_ADMIN_KEY` is correctly set.

**Comment by kaihendry** [comment]
Need logs.

`aws --profile ins-dev logs filter-log-events --log-group-name "meteor" --start-time $(date -d "-10 hours" +%s000)` shows some connectivity issue.

Check https://dashboard.dev.ins.unee-t.com/ is accessible from meteor container @tuananh1508

**Comment by tuananh1508** [comment]
Fixed, we do not have a rule open 443.

**Comment by franck-boullier** [comment]
> Fixed, we do not have a rule open 443.

@tuananh1508 how do we create that rule?

**Comment by franck-boullier** [comment]
Found it.

That works now
