### ISSUE TITLE
Unable to create a new unit

### ISSUE THREAD

**Issue by franck-boullier** [Unee-T-INS/frontend#11]
# The test:

In the MEFE http://case.dev.ins.unee-t.com/unit/new
Test also done on https://case.dev.ins.unee-t.com/unit/new

# Expected result:

The unit is created

## Actual result: 

The unit is NOT created

![image](https://user-images.githubusercontent.com/31331637/72592544-c3dc3b80-393d-11ea-9a05-3e4e7091fe78.png)

## More information:
[Error log is available here](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=meteor;stream=ecs/meteor/afd2eff3-dd08-4d5b-b533-145c8ed599c8;start=2020-01-16T07:07:27Z)

### Error messsage: 
`'Error 1048: Column \'description\' cannot be null\n',`

### in the BZ database:
in the table `ut_data_to_create_units`:
-  The record to create the unit is created as expected: `unit_name`: Policy 1
- `unit_description_details` is not empty or NULL: A test unit

**Comment by franck-boullier** [comment]
# More information:

In the BZ database the product has been created as expected BUT the following things have NOT been created:
- `groups`
- `flagtypes`
- `components`

Each of these table require a field `description` for each record.
It seems that the golang script is passing a NULL value when creating the new records in these tables.

**Comment by franck-boullier** [comment]
# More information:

Reminder that some of the lambda calls are hardcoded in some [Database triggers and procedures](https://github.com/unee-t/bz-database/blob/master/db%20scripts%20to%20add%20objects%20to%20the%20schema/add_all_lambda_related_objects_v5.39.1_DEV_Staging.sql).

We need to make sure that these are also modified so that they will work in a specific environment.

**Comment by franck-boullier** [comment]
# More info:

Using the correct AWS account ID for the Aurora lambda calls did NOT solve the problem!

It seems that some values are passed as NULL to the BZ script that inserts the records associated to a new unit  in one or more of the following BZ tables:
- `groups`
- `flagtypes`
- `components`

**Comment by franck-boullier** [comment]
# More information:

We also need to make sure that the list of dummy user that is created by the procedure `table_to_list_dummy_user_by_environment` is correct.

DONE 
This solved the issue
`'Error 1048: Column \'description\' cannot be null\n',`

**Comment by franck-boullier** [comment]
# New issue:

## Step:

`step: 'INVITE lambda request, unit cleanup might be necessary',`

## Error message:

` { Error: failed [502] {"message": "Internal server error"}`

![image](https://user-images.githubusercontent.com/31331637/72612897-09622e00-3969-11ea-9b63-1e16b1e302bb.png)

**Comment by kaihendry** [comment]
That log appears to be from frontend, but the log from the invite lambda would be useful here for debugging.

https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=/aws/lambda/processinvitations;stream=2020/01/11/[6]e5ac28754b424c9789bb02c252cb7085;start=2020-01-10T07:31:45Z

It would appear the error is *failed to retrieve credentials for looking up MYSQL_USER*

I'm having a hard time working out what's happened in invite code.

**Comment by kaihendry** [comment]
I think I fixed the invite issue by RE-deploying: https://github.com/Unee-T-INS/invite/issues/6 but I didn't see an invite call, so maybe I mis-understood how to reproduce?


Next issue is that lambda trigger stuff I guess is not setup yet or has @tuananh1508 done it?
https://s.natalian.org/2020-01-18/lambda-trigger.mp4

**Comment by franck-boullier** [comment]
> lambda trigger stuff I guess is not setup yet 

@kai, assuming that you're talking about the Lambda calls triggered by Aurora DB procedures and events, these have been set in the BZ database (and they work).

**Comment by kaihendry** [comment]
It's not correctly setup:

```
[hendry@t480s unee-t]$ aws --profile uneet-prod iam list-attached-role-policies --role-name Aurora_access_to_lambda
{
    "AttachedPolicies": [
        {
            "PolicyName": "AWSLambdaFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AWSLambdaFullAccess"
        }
    ]
}
[hendry@t480s unee-t]$ aws --profile uneet-dev iam list-attached-role-policies --role-name Aurora_access_to_lambda
{
    "AttachedPolicies": [
        {
            "PolicyName": "AWSLambdaFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AWSLambdaFullAccess"
        }
    ]
}
[hendry@t480s unee-t]$ aws --profile ins-dev iam list-attached-role-policies --role-name Aurora_access_to_lambda

An error occurred (NoSuchEntity) when calling the ListAttachedRolePolicies operation: The role with name Aurora_access_to_lambda cannot be found.
```

**Comment by franck-boullier** [comment]
> It's not correctly setup:

This means that there is (as of today) a thing that is still mysterious to us and that we need to correctly configure.

Apparently, since it's not done automatically when we deploy the repos, this has to be done manually somehow.

@kaihendry is there any documentation somewhere that we can look at to better understand:
- WHAT it is that we need to setup, 
- WHERE we can do that setup and 
- HOW this setup should be done?

**Comment by tuananh1508** [comment]
Hi @kaihendry, Actually the role is existing. But the name is Aurora_access_to_lambda_role:
aws --profile ins-dev iam list-attached-role-policies --role-name Aurora_access_to_lambda_role
{
    "AttachedPolicies": [
        {
            "PolicyName": "AWSLambdaFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AWSLambdaFullAccess"
        }
    ]
}  

I'll create a new role with the name is: Aurora_access_to_lambda to keep consistency.

**Comment by franck-boullier** [comment]
> Actually the role is existing. But the name is Aurora_access_to_lambda_role

OK, thanks, we never realized that the role name what somehow hardcoded to be `Aurora_access_to_lambda`.
We'll have to keep that in mind in the future

**Comment by tuananh1508** [comment]
@franck-boullier @kaihendry , I changed to Aurora_access_to_lambda. Can you test again?
About invite, we move the make file and up.json.in so it breaks Kai's code. Kai deployed a working version and we'll work on it later.

**Comment by franck-boullier** [comment]
> I changed to Aurora_access_to_lambda

@tuananh1508 can you please clarify HOW you did that and WHERE you did that so we can add this to our documentation. Thanks!

**Comment by kaihendry** [comment]
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.Lambda.html are the instructions for getting lambda triggers from RDS working.

This is the test you should use to confirm it's working: https://github.com/Unee-T-INS/lambda2sqs/pull/5


When I Google the error message, it would appear there is some UI to associate the role that's moved perhaps? https://www.google.com/search?client=firefox-b-d&q=%22Missing+IAM+Credentials+for+specified+aws_default_lambda_role%22

**Comment by franck-boullier** [comment]
> This means that there is (as of today) a thing that is still mysterious to us and that we need to correctly configure.

We also need to make sure that the RDS Cluster is correctly configured:
Cluster need to have the role `aurora_access_to_lambda` added in the "Manage IAM roles" section for the RDS database.

**Comment by franck-boullier** [comment]
# More information:

![image](https://user-images.githubusercontent.com/31331637/72678372-1d7c6b80-3ae0-11ea-973c-e1a9d91b0ee1.png)

Documentation on how to create a Unee-T installation from scratch has been updated to include the missing step.
