### ISSUE TITLE
Unable to create a new case

### ISSUE THREAD

**Issue by franck-boullier** [Unee-T-INS/frontend#12]
# The test:

Create a new case in an existing unit.
- No category.
- No sub-category
- Assign the case to me.

## Expected result:

The case is created 

## Actual result: 

We have an error message:
![image](https://user-images.githubusercontent.com/31331637/72664003-c02ae080-3a33-11ea-929b-592e983b483a.png)

**Comment by franck-boullier** [comment]
# More information:

The error message that mentioned `Lambda API returned error` **is misleading**.
Bug creation does NOT rely on any lambda API. 
Bug creation is done using the native REST API that exists in Bugzilla.

From the [Video](https://s.natalian.org/2020-01-18/lambda-trigger.mp4) from @kaihendry, we can see that the insert statement is called by `opt/bugzilla/Bugzilla/Object.pm` <-- this is the native bugzilla code that should work out of the box.

![image](https://user-images.githubusercontent.com/31331637/72664244-6f68b700-3a36-11ea-8353-da0f70a27dc7.png)

for some (yet) unknown reason it seems that we have an issue with the Bugzilla installation (BZ native REST API are throwing an error).

**Comment by kaihendry** [comment]
"Missing IAM credentials" indicates there is something wrong with the the Aurora lambda trigger setup!

```
[hendry@t480s tests]$ ./call-lambda.sh events/case_updated.json
mysql -h bzdb.dev.ins.unee-t.com -P 3306 -u lambda_invoker --password=dasdsa
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 63996 (HY000) at line 1: Lambda API returned error: Missing IAM Credentials for specified aws_default_lambda_role
NO
```

**Comment by franck-boullier** [comment]
> there is something wrong with the Aurora lambda trigger setup!

@kaihendry OK but since that it seems that you're the only one who's capable of understanding how the credentials and lambda setup should be done, a little more details on this would go a long way to help us...

**Comment by franck-boullier** [comment]
# More information:
Looking at the PROD account it seems that we have several IAM policies created there.

![image](https://user-images.githubusercontent.com/31331637/72675970-e2ba0980-3ac6-11ea-9b3c-299cf99b12b3.png)

The mechanism to create these policies, when these policies should be created and how these policies are used is still unclear at this point.

Out of these 9 IAM policies, 
- 4 have a description that includes `Created by apex (1)` <-- Maybe @kaihendry might be able to give more information about these?
- 2 have no description at all <-- Maybe @kaihendry might be able to give more information about these?
- 3 are related to Quicksight and were created when FBO created QuickSight objects and reports.

**Comment by franck-boullier** [comment]
# More information:

It seems that [Apex is a project that is no longer actively maintained](https://github.com/apex/apex/issues/932).

**Comment by kaihendry** [comment]
Same issue as https://github.com/Unee-T-INS/frontend/issues/11

It's nothing to do with Apex. It's do with the lambda triggers on RDS.

**Comment by franck-boullier** [comment]
We also need to make sure that the RDS Cluster is correctly configured:
Cluster need to have the role aurora_access_to_lambda added in the "Manage IAM roles" section for the RDS database.

Documentation on how to create a Unee-T installation from scratch has been updated to include the missing step.
