### ISSUE TITLE
Unable to upload profile picture for a user

### ISSUE THREAD

**Issue by franck-boullier** [Unee-T-INS/frontend#13]
# The test:

- Go to Unee-T INS >> Profile >> change profile picture (see [this link](http://case.dev.ins.unee-t.com/account-settings)).
- Click on change profile picture
- Upload a picture.

## Expected result:

The profile picture is updated

## Actual result:

The profile picture briefly appears and then disappear.

There seem to be an error message in the browser:
`upload_this_user_avatar_image_file_error`

![image](https://user-images.githubusercontent.com/31331637/72664134-4136a780-3a35-11ea-967f-03de0dab270e.png)

**Comment by franck-boullier** [comment]
After fixing issue #11 and #12 this issue is still there.
Impossible to upload and avatar image.

Error message in the Browser (via the console of the browser) is 
`upload_this_user_avatar_image_file_error`

**Comment by kaihendry** [comment]
Probably the same issue as https://github.com/Unee-T-INS/frontend/issues/14 ... Misconfigured cloudinary setup

**Comment by franck-boullier** [comment]
Fix was the same as for #14 indeed
See https://github.com/Unee-T-INS/frontend/issues/14#issuecomment-577057995
