### ISSUE TITLE
Update Category & Sub-Category list

### ISSUE THREAD

**Issue by sonytrinhcvn** [Unee-T-INS/frontend#21]
Please update the new Category and Sub-Category following the case below:

**Category | Sub-Category**
==================
New business | Quotation
New business | Submission
New business | Payment
New business | Documentation
New business | Other

Renewal | Document
Renewal | Payment
Renewal | Change in policy
Renewal | Other

Endorsement | Addition
Endorsement | Deletion
Endorsement | Documents
Endorsement | Payment/Reimbursement
Endorsement | Other

Claims | Urgent question
Claims | Standard question
Claims | Urgent submission
Claims | Standard submission
Claims | Reimbursement
Claims | Request for LOG
Claims | Investigation
Claims | Other

**Comment by franck-boullier** [comment]
Done
![image](https://user-images.githubusercontent.com/31331637/74598799-3b26fb80-50b3-11ea-8f2f-50d9899789a8.png)

![image](https://user-images.githubusercontent.com/31331637/74598805-5eea4180-50b3-11ea-9b61-7f89c6a3c148.png)
