### ISSUE TITLE
Change label of Radio buttons

### ISSUE THREAD

**Issue by sonytrinhcvn** [Unee-T-INS/frontend#22]
We're missing change label of radio buttons.
Correct mapping should be like:

**Tenant -> My Account manager
Owner/Landlord -> My HR
Contractor -> Policyholder
Management Company -> My Insurer
Agent -> Other**

![image](https://user-images.githubusercontent.com/60875090/74698367-14420400-5230-11ea-8322-1834b03e07d4.png)

**Comment by franck-boullier** [comment]
@nbiton can you have a look at this please?
I'm not sure what we are missing there.

The file [`/imports/api/unit-roles-data.js`](https://github.com/Unee-T-INS/frontend/blob/master/imports/api/unit-roles-data.js) has been updated but the values on display are still incorrect.

Any idea?

**Comment by franck-boullier** [comment]
@sonytrinhcvn the values that are displayed there are the values that were used **when the unit/policy was created**. These values are stored as is in the Mongo collection `UnitRolesData` associated to that unit/policy.

# Example 1: 

The unit/policy was created when the label for the "Tenant" value was "Tenant", then the label displayed in "Tenant".
See this unit:
![image](https://user-images.githubusercontent.com/31331637/74792120-67cb5500-52f7-11ea-891b-ce58f552b934.png)

# Example 2: 

The unit/policy was created when the label for the "Tenant" value was "My Account manager", then the label displayed is "My Account manager".

See This unit:
![image](https://user-images.githubusercontent.com/31331637/74791953-ec69a380-52f6-11ea-8a42-d0d1be595d8e.png)

# How to check that all is working as intended:

- Make sure that the version of the code is using the correct label.
- Create a new unit.
![image](https://user-images.githubusercontent.com/31331637/74792237-d14b6380-52f7-11ea-9eb7-7fdcc138e35b.png)
- Check that the roles are displayed as expected when we create a new case in that unit.
![image](https://user-images.githubusercontent.com/31331637/74792285-f50ea980-52f7-11ea-9cb5-26b66f5e329e.png)


Thanks @nbiton for helping with that issue!
