### ISSUE TITLE
Update text for radio buttons

### ISSUE THREAD

**Issue by sonytrinhcvn** [Unee-T-INS/frontend#23]
Hi, please update the text for radio buttons following below:

**My Account Manager -> The Insurance Agent
My HR -> The HR / Employee Benefit manager
PolicyHolder- > The Policyholder/Beneficiary
My Insurer -> The Insurance company**
Other

**Comment by franck-boullier** [comment]
Done in the BZ database.
@sonytrinhcvn please make sure that the frontend code is updated accordingly too.
