### ISSUE TITLE
Update text for chatbot

### ISSUE THREAD

**Issue by sonytrinhcvn** [Unee-T-INS/frontend#24]
Replace **unit** to **policy**
Remove **the** (An invitation to collaborate on this case has been sent to the)

**Comment by franck-boullier** [comment]
The text for the chatbot is controlled by a SQL procedure.

We need to update the database using the script available [here](https://github.com/Unee-T-INS/bz_database_customization/blob/master/replace_the_term_unit_with_policy.sql).

This should work now, please reopen if there is still an issue.
