### ISSUE TITLE
Links in the email notifications are not working

### ISSUE THREAD

**Issue by sonytrinhcvn** [Unee-T-INS/frontend#26]
We got this email when click **Unsubscribe & Manage your setting**
https://e.dev.ins.unee-t.com/?url=https%3A%2F%2Fcase.dev.ins.unee-t.com%2Fnotification-settings&id=ut_notification_message_new-64&email=trunghieu912003%40gmail.com

**Comment by franck-boullier** [comment]
@sonytrinhcvn can we add a list of:
- all the emails that have problematic urls
- all the URLs that are problematic in these emails.
This will help us test everything when we have implemented the fix.

**Comment by franck-boullier** [comment]
The code to generate the links in the emails is located in the folder 
https://github.com/Unee-T-INS/frontend/tree/master/imports/email-templates.

There are several files that are using a variable `ROOT_URL`.
@sonytrinhcvn can you help me list these files in that GH issue please.

This variable `ROOT_URL` is defined as an environment variable in the files `aws-env.[STAGE]`

**Comment by franck-boullier** [comment]
# The issue:

In the email, the links generated are something like 
`https://e.dev.ins.unee-t.com/?url=https%3A%2F%2Fcase.dev.ins.unee-t.com%2Fnotification-settings&id=ut_notification_message_new-64&email=trunghieu912003%40gmail.com`
instead of 
`https://case.dev.ins.unee-t.com/notification-settings&id=ut_notification_message_new-64&email=trunghieu912003%40gmail.com`

The code somehow:
- includes an unnecessary prefix in the email: `https://e.dev.ins.unee-t.com/?url=https%3A%2F%2F`
- replace `/` with `%2F`

We have 2 solutions to fix the issue:

# Quick and dirty:

- hard code the URLs instead of using variables.

## Pros:

Fast

## Cons:

This will make it harder/almost impossible t use automated deployment anymore

# Proper fix:

- Understand how we can remove the additional code

**Comment by sonytrinhcvn** [comment]
> @sonytrinhcvn can we add a list of:
> 
> * all the emails that have problematic urls
> * all the URLs that are problematic in these emails.
>   This will help us test everything when we have implemented the fix.

Here you are: 

- case-assignee-updated
- case-new-message
- case-updated
- case-user-invited
- new-case-assigned

**Comment by sonytrinhcvn** [comment]
> The code to generate the links in the emails is located in the folder
> https://github.com/Unee-T-INS/frontend/tree/master/imports/email-templates.
> 
> There are several files that are using a variable `ROOT_URL`.
> @sonytrinhcvn can you help me list these files in that GH issue please.
> 
> This variable `ROOT_URL` is defined as an environment variable in the files `aws-env.[STAGE]`

We have some files: 
- case-assignee-updated
- case-new-message
- case-updated
- case-user-invited
- new-case-assigned
- report-pdf-shared
- unit-user-invited
- helper
- email-invite
- logger

**Comment by franck-boullier** [comment]
# More information:

When we redeploy the code, we can update the `ROOT_URL~ in the file `aws-env.[STAGE]`

Today this variable is built from other variables. This might cause some unexpected behavior.

# The Test:

in the DEV environment: replace the current value 
`export ROOT_URL=https://case.$STAGE.$DOMAIN` on https://github.com/Unee-T-INS/frontend/blob/8b5a6e0ddbee6aaca4d2f532ad342d3ee5a5cf3c/aws-env.dev#L38
with
`export ROOT_URL=https://case.dev.ins.unee-t.com`
in the file https://github.com/Unee-T-INS/frontend/blob/master/aws-env.dev

- Re-deploy
- test:
  - create a case
  - invite someone
  - check if links are working.

**Comment by franck-boullier** [comment]
# What was done:

Hotfix (https://github.com/Unee-T-INS/frontend/commit/c2a4d0324796a62de7554ee6e389d338d241637d) done to test hypothesis described in https://github.com/Unee-T-INS/frontend/issues/26#issuecomment-594302518

# Next step:

Test what are the values for the links generated in the emails.
See if we have fixed the issue or improved the situation.

**Comment by franck-boullier** [comment]
# More information:

The URLs are generated using code like
` url: url.resolve(process.env.ROOT_URL, '/notification-settings')`

## `url.resolve`:
a [built-in mechanism in Node JS](https://www.geeksforgeeks.org/node-url-resolvefromto-api/).

From the documentation:

> The url.resolve(from, to) is a builtin method of class URL that resolves a target URL relative to a base URL.
> Syntax:
> 
> url.resolve(from, to);
> 
>     Where,
>     from: (type:String) The base URL being resolved against.
>     to : (type:String) The “href” URL being resolved.
> 
> 

## `process.env.`
Is also a [built-in mechanism in Node JS](https://codeburst.io/process-env-what-it-is-and-why-when-how-to-use-it-effectively-505d0b2831e7).

> The `process.env` global variable is injected by the Node at runtime for your application to use and it represents the state of the system environment your application is in when it starts. For example, if the system has a PATH variable set, this will be made accessible to you through process.env.PATH which you can use to check where binaries are located and make external calls to them if required.

**Comment by sonytrinhcvn** [comment]
# Test 1:
- Create a new policy
- My relationship to the policy: The Insurance Agent
- Create a new case
- Assign this case to The Insurance Agent
## Expect result
- The person assigned to the case receives an email - PASSED
- The email includes a link to the case - PASSED the link was [https://case.dev.ins.unee-t.com/invitation?code=AHfKzw8xtqrw74IhPjVsS1Ja]
- The link to the case sends the user to that case in InsureChat - PASSED

The source code for this email is in the file https://github.com/Unee-T-INS/frontend/blob/master/imports/util/email-invite.js.
The code that is use could generate the url is
https://github.com/Unee-T-INS/frontend/blob/c2a4d0324796a62de7554ee6e389d338d241637d/imports/util/email-invite.js#L52

**Comment by sonytrinhcvn** [comment]
# Test 2:
- Create a new policy
- My relationship to the policy: The Insurance Agent
- Create a new case
- Assign this case to myself
## Expect result
- No email sent - PASSED

**Comment by sonytrinhcvn** [comment]
# Test 3:
- Create a new policy
- My relationship to the policy: The Insurance Agent
- Create a new case
- Assign this case to someone else The Insurance Company
- Enter the email address at the Insurance company
## Expect result
- The person assigned to the case receives an email 
- The email includes a link to the case - the link was []
- The link to the case sends the user to that case in InsureChat

The source code for this email is in the file https://github.com/Unee-T-INS/frontend/blob/master/imports/email-templates/case-assignee-updated.js
The code that is used to generate the URL is
https://github.com/Unee-T-INS/frontend/blob/c2a4d0324796a62de7554ee6e389d338d241637d/imports/email-templates/case-assignee-updated.js#L8-L12

**Comment by sonytrinhcvn** [comment]
# More Information
In the script, https://github.com/Unee-T-INS/frontend/blob/master/imports/email-templates/components/helpers.js refer to a dependency https://github.com/unee-t/engagement this dependency has not been deployed to Unee-T INS

# To do
Deploy unee-t/engagement in the Unee-T INS environment.
Test again

**Comment by franck-boullier** [comment]
# More information:

Quickfix: remove the engagement URL to avoid relying on the engagement repo.
See https://github.com/unee-t/frontend/commit/45c3f63782417eefd668d6e2ee28578cffcf796f for the code that'll work without the engagement URLs.

**Comment by franck-boullier** [comment]
Quickfix described in https://github.com/Unee-T-INS/frontend/issues/26#issuecomment-594474809 has been implemented as part of PR #27.

We need a long term solution when we:
- correctly deploy the `engagement` codebase
- re-activate the `createEngagementLink` function so we can better track user engagement on email sent.

# To Do:

Test the quick fix.

**Comment by franck-boullier** [comment]
The issue has been fixed. See #29 for what we still need to do
