### ISSUE TITLE
email invitation are not received

### ISSUE THREAD

**Issue by franck-boullier** [Unee-T-INS/frontend#38]
# The problem:

- Create a case
- Invite a person to a case

## Expected result:

The invited person receives the invitation email.

## Actual result:

The email is NOT received.

**Comment by franck-boullier** [comment]
# Test if email engine (AWS SES) is working as expected:

- Create a new account
- make sure the email verification is received at the email associated to the account:

PASSED
![image](https://user-images.githubusercontent.com/31331637/78774833-d0fe4900-79c7-11ea-8464-b6b58d053e22.png)

# Conclusion:

The email sending engine (SES) is working as expected.

**Comment by franck-boullier** [comment]
# More information:

- Create a new policy
  - `Test Policy - 08 Apr 2020` DONE
  - Type: `Life` DONE
  - Relationship: `Insurance Agent` DONE
- Create a new case.
  - Case "Assigned to Me"
- Invite someone to the case.
  - fbo test gmail address
  - Relationship: `HR/EMployee Benefit manager`

# Expected result:

- No Error message PASSED
- Email is received FAILED - after 5 mn, the message is NOT received

## Check AWS logs:

There is an error message when the app is processing the invitation:
```
{
    "fields": {
        "app": "processinvitations",
        "commit": "ins.v1.1.0",
        "duration": 144,
        "id": "78732709-4979-4ec6-bf25-5e0725e17878",
        "ip": "3.0.40.57",
        "method": "GET",
        "path": "/",
        "plugin": "logs",
        "query": "",
        "region": "ap-southeast-1",
        "size": 4,
        "stage": "production",
        "status": 500,
        "version": "4"
    },
    "level": "error",
    "timestamp": "2020-04-08T10:42:40.47573295Z",
    "message": "response"
}
```

**Comment by franck-boullier** [comment]
# Investigate the code `processinvitation`:

This code is maintained in the `invite` repo.
The variable for the email address for the "send from" email was incorrect.

Release of a hotfix for that. See the [Hotfix](https://github.com/Unee-T-INS/invite/releases/tag/ins.v1.1.2) for more details.
Also see commit https://github.com/Unee-T-INS/invite/commit/6f46a8c61223978743161be991dfe399e40a9faf

# Additional fix:

The code in the repo `apienroll` also uses the incorrect email address for the "send from" email address.

Release of a hotfix for that. See the [Hotfix](https://github.com/Unee-T-INS/apienroll/releases/tag/ins.v1.1.4) for more details.
Also see commit https://github.com/Unee-T-INS/apienroll/commit/16659a522bf2589d4e846fc6807129f3604c1bea

**Comment by franck-boullier** [comment]
# Test again:

- Use the same [case](https://case.insurechat.io/case/5/details/invite/new)
- Invite another user fb test gmail address
- Role Policy holder.

## Expected result:

- No Error message - PASSED
- The invited person should receive a notification - FAILED
- Log message should show a different version of the process invitation - PASSED
```
{
    "fields": {
        "app": "processinvitations",
        "commit": "ins.v1.1.0", <-- DIFFERENT VERSION EXPECTED
(...)
```

## Actual result:

- email is not received.
We still have an error message with the "processinvitations" lambda
at 2020-04-08 12:01:38
```
{
    "fields": {
        "app": "processinvitations",
        "commit": "ins.v1.1.2",
        "duration": 102,
        "id": "90a28931-c62c-4695-a63b-97cdbda56a20",
        "ip": "3.0.40.57",
        "method": "GET",
        "path": "/",
        "plugin": "logs",
        "query": "",
        "region": "ap-southeast-1",
        "size": 4,
        "stage": "production",
        "status": 500,
        "version": "5"
    },
    "level": "error",
    "timestamp": "2020-04-08T12:01:38.285446285Z",
    "message": "response"
}
```

**Comment by franck-boullier** [comment]
# More Tests:

Check at which point this is failing
- Log in to InsureChat as one of the invited user

# Expected result:

- The user can see the case he/she was invited to

## Actual result:

- The invited user CAN reset his password <-- the user has been created as expected.
- The invited user does NOT see the **case** he was invited to <-- he does NOT have permission to see the case.
- The invited user does NOT see the **unit** he was invited to <-- he does NOT have permission to see the unit.

# To do:

- Explore the SQL database to see if the issue happens here for some reason.

**Comment by franck-boullier** [comment]
# Analysis of what happens in the SQL:

- The table `ut_data_to_add_user_to_a_case` is NOT populated.
- The table `ut_data_to_add_user_to_a_role` is NOT populated.

This is why:
- Invited users can't access the case.
- Invited users can't access the unit.
- email notification is not sent.

**Comment by franck-boullier** [comment]
# TODO:

check the security groups for the Subnets that should be allowed to access `lambda-to-rds`.

There are **2** Network interface for each of the subnet IDs and **BOTH** network interfaces should belong to the `lambda-to-rds` security group.

Update security groups for each NI <-- DONE

# Test again:

- Use the same [case](https://case.insurechat.io/case/5/details/invite/new)
- Invite another user fb test gmail address
- Role: Insurance Company.

## Expected result:

- No Error message - PASSED
- The invited person should receive a notification - FAILED
- The table `ut_data_to_add_user_to_a_case` should have a new record - FAILED
- The table `ut_data_to_add_user_to_a_role` should have a new record - FAILED

**Comment by franck-boullier** [comment]
# TODO:

Check if this is a permission issue.
Open Default security group to all traffic to the world

# Test again:

- Use the same [case](https://case.insurechat.io/case/5/details/invite/new)
- Invite another user fb test gmail address
- Role: Other.

## Expected result:

- No Error message - PASSED
- The invited person should receive a notification - FAILED
- The table `ut_data_to_add_user_to_a_case` should have a new record - FAILED
- The table `ut_data_to_add_user_to_a_role` should have a new record - FAILED

# Actual result:

This does NOT work <-- does NOT seem to be related to permissions...

**Comment by franck-boullier** [comment]
Error log available [here](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEventViewer:group=/aws/lambda/processinvitations;stream=2020/04/08/%5B5%5D1f3d213f5e904e798873ca0ea8653310;start=2020-04-07T12:54:32Z) for the latest request

```
{
    "fields": {
        "app": "processinvitations",
        "commit": "ins.v1.1.2",
        "duration": 75,
        "id": "b421b930-5b4a-4483-b95c-fc8cd98e68e9",
        "ip": "13.250.32.72",
        "method": "GET",
        "path": "/",
        "plugin": "logs",
        "query": "",
        "region": "ap-southeast-1",
        "size": 4,
        "stage": "production",
        "status": 500,
        "version": "5"
    },
    "level": "error",
    "timestamp": "2020-04-08T13:01:07.802527848Z",
    "message": "response"
}
```

**Comment by kaihendry** [comment]
Did it work before? Did a change break it?

How do you test it is working?
Does https://invite.dev.ins.unee-t.com/health_check work with the right bearer token?

This bug should probably be in
https://github.com/Unee-T-INS/invite/releases

**Comment by franck-boullier** [comment]
> Did it work before? 

Everything worked in the DEV

> Did a change break it?

Not that I can tell.

> How do you test it is working?

See https://github.com/Unee-T-INS/frontend/issues/38#issue-596478041

> Does https://invite.dev.ins.unee-t.com/health_check work with the right bearer token?

Not sure how to use this health check: I could not find any instruction on how this should be used.
Specifically there are no instruction or documentation that I could find about:
- What is the "right bearer token"? 
- Where is it possible to find the "right bearer token"? and 
- How and where to specify the "right bearer token"?

Going to the correct url (https://invite.insurechat.com/health_check) results in this.
![image](https://user-images.githubusercontent.com/31331637/78853269-09963500-7a51-11ea-94c0-bb2082c2ce2e.png)

**Comment by kaihendry** [comment]
https://invite.insurechat.com/health_check is incorrect.

    curl -H "Authorization: Bearer $(ssm ins-prod API_ACCESS_TOKEN)" https://invite.insurechat.io/metrics

**Comment by franck-boullier** [comment]
# Check if we have an issue with the API key:

- Redeploy the front end code - DONE
- Create a new case - DONE (see [case](https://case.insurechat.io/case/6))
- Invite a new user to the case:
  - fb email test gmail
  - role HR.Employee Benefit manager

## Expected result:
 
- No Error message - PASSED
- The invited person should receive a notification - FAILED
- The table `ut_data_to_add_user_to_a_case` should have a new record - FAILED
- The table `ut_data_to_add_user_to_a_role` should have a new record - FAILED

# Actual result:

- This is still NOT working, API key is NOT the issue there...

**Comment by kaihendry** [comment]
It's failing here https://github.com/Unee-T-INS/invite/blob/master/invite.go#L473

GET triggers the invite lambda to fetch and process pending invites from MEFE. This fetch is failing AFAICT.

```
]$ curl -i -X GET -H "Authorization: Bearer $(ssm ins-prod API_ACCESS_TOKEN)" https://invite.insurechat.io/
HTTP/2 500
content-type: text/plain; charset=utf-8
content-length: 4
date: Thu, 09 Apr 2020 05:34:32 GMT
x-amzn-requestid: 6949dccb-30e1-4cf8-ba5e-ffb4b4d4070d
x-amzn-remapped-content-length: 4
x-amz-apigw-id: KtEMXGbmyQ0Fjfg=
vary: Accept-Encoding
x-content-type-options: nosniff
x-powered-by: up
x-amzn-trace-id: Root=1-5e8eb3e8-c437c7603cb7865df5ecb8ff;Sampled=0
x-amzn-remapped-date: Thu, 09 Apr 2020 05:34:32 GMT
x-cache: Error from cloudfront
via: 1.1 aa0f507eb11fe6a0d0b6bc93ffd294fb.cloudfront.net (CloudFront)
x-amz-cf-pop: SIN5-C1
x-amz-cf-id: 5pILHbiREHbaCI8uzzaAQgoavkr8bCXAPFRRo6h53ZEoxxfdGjpQXw==

EOF

```

It appears it can't fetch the invites from MEFE?

```
curl -i "https://case.insurechat.io/api/pending-invitations?accessToken=$(ssm ins-prod API_ACCESS_TOKEN)"
HTTP/2 401
```

**Comment by franck-boullier** [comment]
# More information:

The command
```
curl -i "https://case.insurechat.io/api/pending-invitations?accessToken=API_ACCESS_TOKEN"
```
Does NOT work

BUT

The command
```
curl -i "http://mefe-432577350.ap-southeast-1.elb.amazonaws.com/api/pending-invitations?accessToken=API_ACCESS_TOKEN"
```

DOES work!

This seems to point to an issue with the DNS record for `case.insurechat.io`

# TODO:

Update the DNS record for `case` to use `mefe-432577350.ap-southeast-1.elb.amazonaws.com` (the Alias for the ELB). <-- DONE

Test invitation again.

**Comment by franck-boullier** [comment]
# The tests:

- Check that the curl test is working
```
curl -i "https://case.insurechat.io/api/pending-invitations?accessToken=API_ACCESS_TOKEN"
```
PASSED

Create a new invitation:

- Invite a new user to the case:
  - fb email test gmail
  - role: Insurance Cny

## Expected result:
 
- No Error message in the MEFE - PASSED
- No Error in the Cloudwatch log for `processinvitations` - PASSED
- The invited person should receive a notification - FAILED
- The table `ut_data_to_add_user_to_a_case` should have a new record - FAILED
- The table `ut_data_to_add_user_to_a_role` should have a new record - FAILED

# Actual result:

- No more error from the `processinvitations` log group
```
{
    "fields": {
        "app": "processinvitations",
        "commit": "ins.v1.1.2",
        "duration": 153,
        "id": "05284482-d190-4551-9c3c-14c120686948",
        "ip": "13.250.32.72",
        "method": "GET",
        "path": "/",
        "plugin": "logs",
        "query": "",
        "region": "ap-southeast-1",
        "size": 10,
        "stage": "production",
        "status": 200,
        "version": "5"
    },
    "level": "info",
    "timestamp": "2020-04-09T08:37:08.053099051Z",
    "message": "response"
}
```
- There are 14 messages availalble in the SQS queue

This is progress but the process seems to fail AFTER the messages are sent to the SQS queue for some reasons...

**Comment by franck-boullier** [comment]
# Redeploy the [lambda2sqs](https://github.com/Unee-T-INS/lambda2sqs) code:

The code in the repo `lambd2sqs` relies on some variables from the AWS parameter store.

Redeploy the code to make sure we use the latest version of the variables
Release of a hotfix for that. See the [Hotfix](https://github.com/Unee-T-INS/lambda2sqs/releases/tag/ins.v1.1.1) for more details.

We need to check if the code is using the correct variables there...

**Comment by franck-boullier** [comment]
# The solution:

The issue was with the SQS configuration of the `invites` queue.
The SQS `invites` queue needs to have its Lambda trigger configured.
Lambda trigger should be xxx:invitefromqueue_invite.

Once the trigger is added, the queue is correctly processed.
