### ISSUE TITLE
Error while building Docker image

### ISSUE THREAD

**Issue by franck-boullier** [Unee-T-INS/frontend#8]
Error message from [Travis CI](https://travis-ci.org/Unee-T-INS/frontend/builds/636765152): 

`node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v72-linux-x64.tar.gz`

**Comment by franck-boullier** [comment]
Some comments on GH about this issue.
https://github.com/kelektiv/node.bcrypt.js/issues/572

**Comment by tuananh1508** [comment]
Can we trigger a build on Unee-t Dev env to check if the issues occur on all Installations or only in INS.
- If the build is a success, So It means the issue only occurs with INS
- If the build is false, It will be deployed to dev, and means this issue occurs with all installation.

**Comment by tuananh1508** [comment]
I Change bcrypt version to 3.0.6 and It works, But I'm not sure Frontend works properly with bcrypt:3.0.6, this is a temporary solution.

**Comment by franck-boullier** [comment]
See https://github.com/Unee-T-INS/frontend/pull/7/commits/caa65367e27bc6461c7c7512be68de14d57c1af9 for how we solved this issue,

TO DO: check that MEFE works as expected.
